### ISSUE TITLE
Refactoring - Replace Magic Number with Symbolic Constant

### ISSUE THREAD

**Issue by katumbac** [santiagobaronz/Alquiler-de-vehiculos#6]
https://github.com/santiagobaronz/Alquiler-de-vehiculos/blob/7126e158f0434bb75a01ab99dc34a2226c63d917/src/main/java/co/edu/udistrital/poo/Clases/Camion.java#L28-L31

En el método `precioAlquiler`, se utiliza el número 50 y 40 para calcular el precio del alquiler de un camión. En lugar de usar estos números directamente, se puede reemplazarlos con constantes simbólicas para hacer el código más legible y mantenible.
Se han creado dos constantes simbólicas `PRECIO_DIARIO_CAMION` y `CARGO_ADICIONAL_CAMION` para reemplazar los números mágicos 50 y 40.
![image](https://github.com/santiagobaronz/Alquiler-de-vehiculos/assets/93357018/b08d819d-7026-4205-9d8e-ebd67f4c3a00)

**Comment by santiagobaronz** [comment]
> https://github.com/santiagobaronz/Alquiler-de-vehiculos/blob/7126e158f0434bb75a01ab99dc34a2226c63d917/src/main/java/co/edu/udistrital/poo/Clases/Camion.java#L28-L31
> 
> En el método `precioAlquiler`, se utiliza el número 50 y 40 para calcular el precio del alquiler de un camión. En lugar de usar estos números directamente, se puede reemplazarlos con constantes simbólicas para hacer el código más legible y mantenible. Se han creado dos constantes simbólicas `PRECIO_DIARIO_CAMION` y `CARGO_ADICIONAL_CAMION` para reemplazar los números mágicos 50 y 40. ![image](https://user-images.githubusercontent.com/93357018/260276947-b08d819d-7026-4205-9d8e-ebd67f4c3a00.png)

Hola, ¿Estas haciendo una tarea de la universidad de revisar mi proyecto o algo? Jajaja es que es muy raro tantos issues abiertos

**Comment by santiagobaronz** [comment]
> https://github.com/santiagobaronz/Alquiler-de-vehiculos/blob/7126e158f0434bb75a01ab99dc34a2226c63d917/src/main/java/co/edu/udistrital/poo/Clases/Camion.java#L28-L31
> 
> En el método `precioAlquiler`, se utiliza el número 50 y 40 para calcular el precio del alquiler de un camión. En lugar de usar estos números directamente, se puede reemplazarlos con constantes simbólicas para hacer el código más legible y mantenible. Se han creado dos constantes simbólicas `PRECIO_DIARIO_CAMION` y `CARGO_ADICIONAL_CAMION` para reemplazar los números mágicos 50 y 40. ![image](https://user-images.githubusercontent.com/93357018/260276947-b08d819d-7026-4205-9d8e-ebd67f4c3a00.png)

Hola, ¿Estas haciendo una tarea de la universidad de revisar mi proyecto o algo? Jajaja es que es muy raro tantos issues abiertos
